variables:
  KANIKO_CACHE_ARGS: "--cache=true --cache-copy-layers=true --cache-ttl=24h"

stages:
  - build-base
  - build-nginx
  - build-nginx-php

.build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    CONTEXT_DIR: $CI_PROJECT_DIR/$IMAGE_NAME
    IMAGE_PREFIX: $CI_REGISTRY_IMAGE
    DOCKERFILE: Dockerfile
  script:
    - tags="$(awk -F= '/^tags\s*=\s*/{print $2}' "$CONTEXT_DIR/.release" | head -n 1)"
    - tags="$([ -n "$tags" ] && echo "$tags" || date -u +"%Y-%m-%d")"
    - destination_flags="$(for t in $tags; do echo -n "--destination $CI_REGISTRY_IMAGE/$IMAGE_NAME:$t "; done)"
    - mkdir -p /kaniko/.docker
    - |
      cat <<-EOF >/kaniko/.docker/config.json
      {
          "auths": {
              "$CI_REGISTRY": {
                  "auth": "$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)"
              },
              "${CI_DEPENDENCY_PROXY_SERVER%:*}": {
                  "auth": "$(echo -n ${CI_DEPENDENCY_PROXY_USER}:${CI_DEPENDENCY_PROXY_PASSWORD} | base64)"
              }
          }
      }
      EOF
    #- echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
        --context $CONTEXT_DIR
        --dockerfile $CONTEXT_DIR/$DOCKERFILE
        --build-arg IMAGE_PREFIX=$IMAGE_PREFIX
        --reproducible
        $KANIKO_CACHE_ARGS
        $destination_flags
  rules:
    - if: $CI_COMMIT_TAG =~ /$IMAGE_NAME\+/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

build:base-alpine:
  extends: .build
  stage: build-base
  variables:
    IMAGE_NAME: base-alpine
    IMAGE_PREFIX: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX

build:nginx:
  extends: .build
  stage: build-nginx
  # needs: ["build:base-alpine"]
  variables:
    IMAGE_NAME: nginx

build:nginx-php7:
  extends: .build
  stage: build-nginx-php
  needs: ["build:nginx"]
  variables:
    IMAGE_NAME: nginx-php7
