#!/usr/bin/env bash
set -eo pipefail

(
cd "$(dirname $(readlink -f "$0"))"

# import bash-cli
. ".bash-cli/bash-cli.inc.sh"

if [[ $# > 0 ]]; then
    case "$1" in
        -h|--help) eval set -- "help"; exit 0;;
    esac
fi

bcli_entrypoint "$@"
)
