#!/bin/bash
set -e

USAGE="Usage: run [OPTIONS]

Provision the container and execute the init process

Options:
  -h, --help           Show this help message and exit
"

# parse cli args
while [[ $# > 0 ]]; do
    case "$1" in
        -h|--help)
            echo "$USAGE"
            exit 0
            ;;
        *)
            echo "Unknown option '$1'"
            exit 1
            ;;
    esac
done

. /provision/cmds/provision $@
. /provision/cmds/start $@
