#!/usr/bin/env bash

build_image() {
    local name="$1"
    (
        cd "$PWD/$name"
        local DOCKERFILE=Dockerfile
        local TAGS="$(get_tags)"
        local NAME="$USERNAME/$(get_name)"
        if [[ -n "$PREFIX" ]]; then
            NAME="$PREFIX/$NAME"
        fi

        if has_changes && [[ $FORCE == false ]]; then
            if ! confirm "Working directory '$name' not clean. Build anyway?"; then
                exit 0
            fi
        fi

        if [[ $DEPENDENCIES == true ]]; then
            local dependency="$(grep -E "^FROM.*aisberg/.*" Dockerfile | sed -r "s|.*/(.*):.*|\1|" | tail -n1 || echo "")"
            echo $dependency
            if [[ -n "$dependency" ]]; then
                (
                    cd ..
                    build_image "$dependency"
                )
            fi
        fi

        echo "################################################################################"
        echo "# Building Image '$NAME'"
        echo "################################################################################"

        local TAG_LIST=""
        for t in $TAGS; do
            TAG_LIST="$TAG_LIST -t $NAME:$t"
        done
        local BUILD_ARG=$([ -n "$PREFIX" ] && echo "--build-arg=IMAGE_PREFIX=$PREFIX" || echo "")

        docker build \
            $TAG_LIST \
            -f "$DOCKERFILE" \
            $BUILD_ARG \
            $OPTIONS \
            .
    )
}


INC_DIR="$PWD/.bash-cli"
. "$INC_DIR/bash-cli.inc.sh"
. "$INC_DIR/func.sh"

PREFIX=""
USERNAME="aisberg"
DEPENDENCIES=false
FORCE=false
OPTIONS=""

args=$(getopt -n "cli create image" -o "h,p:,u:,d,f,o:" -l "help,prefix:,username:,dependencies,force,options:" -- "$@")
eval set -- "$args"
while [[ $# > 0 ]]; do
    case "$1" in
        -h|--help) "$INC_DIR/help" cli create image; exit 0;;
        -p|--prefix) PREFIX="$2"; shift 2;;
        -u|--username) USERNAME="$2"; shift 2;;
        -d|--dependencies) DEPENDENCIES=true; shift;;
        -f|--force) FORCE=true; shift;;
        -o|--options) OPTIONS="$2"; shift 2;;
        --) shift; break;;
        *) echo "Unknown option '$1'"; exit 1;;
    esac
done
if [[ $# > 0 ]]; then DIR="$@"; shift; else echo "Missing DIR argument"; exit 1; fi
for d in $DIR; do
    if [[ ! -d "$PWD/$d" ]]; then echo "Directory doesn't exist: '$PWD/$d'"; exit 1; fi
    if [[ ! -f "$PWD/$d/.release" ]]; then echo "Release file doesn't exist: '$PWD/$d/.release'"; exit 1; fi
done


for d in $DIR; do
    build_image "$d"
done
