#!/bin/bash
set -e

# copy configuration files depending on operation mode
copy_autogenerated_files /tmp/burp/$BURP_MODE /data/burp

# set permissions
chmod 0600 /data/burp/burp.conf
if [[ "$BURP_MODE" == server ]]; then
    chmod 0750 /data/burp/notify.sh
elif [[ "$BURP_MODE" == client ]]; then
    chmod 0700 \
        /data/burp/pre-backup.sh \
        /data/burp/post-backup.sh
fi

# cleanup
rm -rf /tmp/burp
