#!/bin/bash
set -e

copy_autogenerated_files /tmp/burp/$BURP_MODE /data/burp
rm -rf /tmp/burp

chmod 0600 /data/burp/burp.conf

if [[ "$BURP_MODE" == client ]]; then
    chmod 0700 \
        /data/burp/pre-backup.sh \
        /data/burp/post-backup.sh
fi
