#!/bin/bash

USAGE="Usage: debug [OPTIONS]

Enter debug mode (drop into bash)

Options:
  -h, --help           Show this help message and exit
"

# parse cli args
while [[ $# > 0 ]]; do
    case "$1" in
        -h|--help)
            echo "$USAGE"
            exit 0
            ;;
        *)
            echo "Unknown option '$1'"
            exit 1
            ;;
    esac
done

print_debug "Entering debug mode"
exec /bin/bash
