
LABEL org.opencontainers.image.title="Base Image - Ubuntu" \
    org.opencontainers.image.version="%%IMAGE_VERSION%%" \
    org.opencontainers.image.description="A base image build upon Ubuntu" \
    org.opencontainers.image.url="https://www.ubuntu.com" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.authors="Andre Lehmann <aisberg@posteo.de>" \
    org.opencontainers.image.source="https://github.com/Aisbergg/dockerfiles/base"
