FROM golang:alpine as build
WORKDIR /usr/local/src
RUN apk add --update --no-cache --no-progress git &&\
    go get -v -u github.com/ochinchina/supervisord &&\
    CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-extldflags -static" -o /usr/bin/supervisord github.com/ochinchina/supervisord

#-------------------------------------------------------------------------------

FROM alpine:3.7

ARG CREATED
ARG LANG=en_US.UTF-8

LABEL org.opencontainers.image.title="Base Image - Alpine Linux" \
    org.opencontainers.image.version="3.7" \
    org.opencontainers.image.description="A base image build upon Alpine Linux" \
    org.opencontainers.image.url="https://www.alpinelinux.org" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.authors="Andre Lehmann <aisberg@posteo.de>" \
    org.opencontainers.image.source="https://github.com/Aisbergg/dockerfiles/base" \
    org.opencontainers.image.created="$CREATED"

ENV LANG=$LANG \
    LANGUAGE=$LANG \
    LC_ALL=$LANG

COPY --from=build /usr/bin/supervisord /usr/bin/supervisord

RUN apk update && apk upgrade &&\
    apk add --update --no-cache --no-progress  \
        bash \
        ca-certificates \
        git \
        gnupg \
        nano \
        python3 \
        runit \
        shadow \
        tini \
        unzip \
        wget \
        xz &&\
    pip3 install --upgrade pip &&\
    pip3 install wheel &&\
    pip3 install supervisor-logging &&\
    pip3 install supervisor-logstash-notifier &&\
    pip3 install git+https://github.com/Aisbergg/python-templer.git@v1.0.2 &&\
    pip3 install git+https://github.com/Aisbergg/python-confmerge.git@v0.1.1

COPY provision /provision
COPY static/ /
RUN mkdir -p \
        /etc/supervisor/conf.d \
        /usr/local/src \
        /var/log/supervisor \
        /var/run/supervisor &&\
    find /provision -type f -exec chmod 0664 {} + &&\
    find /provision -type d -exec chmod 0775 {} + &&\
    chmod 0644 /etc/bash.bashrc &&\
    chmod 0755 /entrypoint

ENTRYPOINT ["/entrypoint"]
CMD ["run"]
