FROM alpine:3.7

ARG CREATED
ARG LANG=en_US.UTF-8

LABEL org.opencontainers.image.title="Base" \
    org.opencontainers.image.version="3.7" \
    org.opencontainers.image.description="Base Alpine Image" \
    org.opencontainers.image.url="https://www.alpinelinux.org" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.authors="Andre Lehmann <aisberg@posteo.de>" \
    org.opencontainers.image.source="https://github.com/Aisbergg/dockerfiles/base" \
    org.opencontainers.image.created="$CREATED"

ENV LANG=$LANG \
    LANGUAGE=$LANG \
    LC_ALL=$LANG

RUN apk update && apk upgrade &&\
    apk add --update --no-cache --no-progress  \
        bash \
        ca-certificates \
        git \
        gnupg \
        nano \
        python3 \
        runit \
        shadow \
        tini \
        unzip \
        wget \
        xz &&\
    pip3 install git+https://github.com/Aisbergg/python-templer.git@v1.0.2 &&\
    pip3 install git+https://github.com/Aisbergg/python-confmerge.git@v0.1.1

COPY provision/ /provision
COPY static/ /
RUN mkdir -p /usr/local/src &&\
    find /provision -type f -exec chmod 0664 {} + &&\
    find /provision -type d -exec chmod 0775 {} + &&\
    chmod 0644 /etc/bash.bashrc &&\
    chmod 0755 /entrypoint &&\
    `# replacement for stdout and stderr` &&\
    mkfifo -m 666 /var/log/logpipe

ENTRYPOINT ["/entrypoint"]
CMD ["run"]
