
LABEL org.opencontainers.image.title="Base Image - Alpine Linux" \
    org.opencontainers.image.version="%%IMAGE_VERSION%%" \
    org.opencontainers.image.description="A base image build upon Alpine Linux" \
    org.opencontainers.image.url="https://www.alpinelinux.org" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.authors="Andre Lehmann <aisberg@posteo.de>" \
    org.opencontainers.image.source="https://github.com/aisbergg/dockerfiles/base"
