FROM golang:alpine as build
WORKDIR /usr/local/src
RUN apk add --update --no-cache --no-progress git &&\
    go get -v -u github.com/ochinchina/supervisord &&\
    go get -v -u github.com/papertrail/remote_syslog2 &&\
    CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-extldflags -static" -o /usr/bin/supervisord github.com/ochinchina/supervisord &&\
    CGO_ENABLED=0 GOOS=linux go build -a -ldflags="-extldflags -static" -o /usr/bin/remote_syslog github.com/papertrail/remote_syslog2

#-------------------------------------------------------------------------------

FROM ubuntu:17.10

ARG LANG=en_US.UTF-8
ARG APT_CACHER_NG
ARG UBUNTU_MIRROR=http://archive.ubuntu.com/ubuntu/
ENV TERM=xterm \
    DEBIAN_FRONTEND=noninteractive \
    LANG=$LANG \
    LC_ALL=$LANG \
    TINI_VERSION=v0.17.0 \
    TINI_PGP_KEY_ID=595E85A6B1B4779EA4DAAEC70B588DFF0527A9B7

COPY --from=build /usr/bin/supervisord /usr/bin/supervisord
COPY --from=build /usr/bin/remote_syslog /usr/bin/remote_syslog

RUN useradd -r -u 999 -G root cu &&\
    echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends &&\
    echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends &&\
    echo "deb $UBUNTU_MIRROR artful main universe multiverse restricted\ndeb $UBUNTU_MIRROR artful-updates main universe multiverse restricted\ndeb $UBUNTU_MIRROR artful-backports main universe multiverse restricted\ndeb $UBUNTU_MIRROR artful-security main universe multiverse" > /etc/apt/sources.list &&\
    if [ -n "$APT_CACHER_NG" ]; then echo "Acquire::http { Proxy \"$APT_CACHER_NG\"; };" >> /etc/apt/apt.conf.d/01proxy; fi &&\
    apt-get update &&\
    `#----- fix some problems -----#` &&\
    dpkg-divert --local --rename --add /sbin/initctl &&\
    ln -sf /bin/true /sbin/initctl &&\
    dpkg-divert --local --rename --add /usr/bin/ischroot &&\
    ln -sf /bin/true /usr/bin/ischroot &&\
    unset http_proxy https_proxy &&\
    `#----- generate locales -----#` &&\
    apt-get install -y locales &&\
    sed -i -e "s/# $LANG/$LANG/" /etc/locale.gen &&\
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale language=$LANG &&\
    `#----- install packages -----#` &&\
    apt-get install -y \
        ca-certificates \
        curl \
        dirmngr \
        git \
        iputils-ping \
        nano \
        python3 \
        python3-pip \
        python3-setuptools \
        python3-wheel &&\
    curl -s -o /sbin/tini "https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini" &&\
    curl -s -o /tmp/tini.asc "https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini.asc" &&\
    ( gpg --keyserver ipv4.pool.sks-keyservers.net --keyserver-options timeout=10 --recv-keys "$TINI_PGP_KEY_ID" \
        || gpg --keyserver pgp.mit.edu --keyserver-options timeout=10 --recv-keys "$TINI_PGP_KEY_ID" \
        || gpg --keyserver keyserver.pgp.com --keyserver-options timeout=10 --recv-keys "$TINI_PGP_KEY_ID" ) &&\
    gpg --verify /tmp/tini.asc /sbin/tini &&\
    pip3 install --upgrade pip &&\
    pip3 install git+https://github.com/Aisbergg/python-templer.git@v1.1.1 &&\
    pip3 install git+https://github.com/Aisbergg/python-confmerge.git@v0.2.0 &&\
    `#----- cleanup -----#` &&\
    rm -rf /var/lib/apt/lists/* /var/cache/* /tmp/tini.asc

COPY provision /provision
COPY static /
RUN chmod 0755 /entrypoint /usr/bin/workdirs &&\
    find /provision -type f -exec chmod 0664 {} + &&\
    find /provision -type d -exec chmod 0775 {} + &&\
    workdirs \
        /etc/remote_syslog \
        /etc/supervisor \
        /usr/local/src \
        /var/log \
        /var/log/supervisor \
        /var/run/supervisor

ENTRYPOINT ["/entrypoint"]
CMD ["run"]

ARG CREATED
LABEL org.opencontainers.image.title="Base Image - Ubuntu" \
    org.opencontainers.image.version="17.10" \
    org.opencontainers.image.description="A base image build upon Ubuntu" \
    org.opencontainers.image.url="https://www.ubuntu.com" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.authors="Andre Lehmann <aisberg@posteo.de>" \
    org.opencontainers.image.source="https://github.com/Aisbergg/dockerfiles/base" \
    org.opencontainers.image.created="$CREATED"
