FROM golang:alpine as build
WORKDIR /usr/local/src
RUN apk add --update --no-cache --no-progress git &&\
    go get -v -u github.com/ochinchina/supervisord &&\
    CGO_ENABLED=0 GOOS=linux go build -a -ldflags "-extldflags -static" -o /usr/bin/supervisord github.com/ochinchina/supervisord

#-------------------------------------------------------------------------------

FROM alpine:3.7

ARG LANG=en_US.UTF-8
ARG ALPINE_MIRROR=http://dl-cdn.alpinelinux.org/alpine/v3.7/
ENV LANG=$LANG \
    LANGUAGE=$LANG \
    LC_ALL=$LANG \
    TZ=:/etc/localtime

COPY --from=build /usr/bin/supervisord /usr/bin/supervisord

RUN \
    # add container user (cu)
    adduser -S -u 999 -s /bin/bash -G root cu &&\
    chmod g+rwX /home/cu &&\
    \
    # install software
    { \
        echo "${ALPINE_MIRROR}main"; \
        echo "${ALPINE_MIRROR}community"; \
    } > /etc/apk/repositories &&\
    apk update && apk upgrade &&\
    apk add --update --no-cache --no-progress  \
        bash \
        ca-certificates \
        curl \
        git \
        gnupg \
        nano \
        python3 \
        tini &&\
    ln -sf /usr/bin/python3 /usr/bin/python &&\
    pip3 install --upgrade pip &&\
    pip3 install wheel &&\
    pip3 install schedule &&\
    pip3 install git+https://github.com/Aisbergg/python-templer.git@v1.1.4 &&\
    pip3 install git+https://github.com/Aisbergg/python-confmerge.git@v0.2.0

COPY provision /provision
COPY static /
RUN chmod 0755 /entrypoint /usr/bin/workdirs /usr/bin/schedule_program &&\
    find /provision -type f -exec chmod 0664 {} + &&\
    find /provision -type d -exec chmod 0775 {} + &&\
    \
    # prepare working directories
    workdirs \
        /container/log \
        /etc/supervisor \
        /usr/local/src \
        /var/run/container

ENTRYPOINT ["/entrypoint"]
CMD ["run"]

ARG CREATED
LABEL org.opencontainers.image.title="Base Image - Alpine Linux" \
    org.opencontainers.image.version="3.7" \
    org.opencontainers.image.description="A base image build upon Alpine Linux" \
    org.opencontainers.image.url="https://www.alpinelinux.org" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.authors="Andre Lehmann <aisberg@posteo.de>" \
    org.opencontainers.image.source="https://github.com/Aisbergg/dockerfiles/base" \
    org.opencontainers.image.created="$CREATED"
